name = "case_i"
version = "0.1.0"
defaultTargets = ["CaseI"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.flexible = false
weak.linter.style.header = false

[[require]]
name = "groebner"
git = "https://github.com/WuProver/groebner_proj.git"
rev = "casei-statements"

[[lean_lib]]
name = "CaseI"
